### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by merangelik** [EuroMOMOnetwork/MOMO#4]
Is there any documentation (like a vignette - or something like https://github.com/thl-mjv/euromomo/blob/master/dev/momomaster.R) available on how to use your package? And what is your connection to https://github.com/thl-mjv/euromomo ?

**Comment by JensXII** [comment]
Hi Angelika,

Sorry, but https://github.com/thl-mjv has nothing directly to do with the EuroMOMO project (https://github.com/EuroMOMOnetwork) or me (https://github.com/JensXII), and we don’t know or can take responsibility for anything concerning that user.

Take care
  Jens

**Comment by merangelik** [comment]
Thank you Jens, 

is there some documentation available on how to use your package? Vignette, examples, more details on the parameteres,... something of that kind?

Best regards,
Angelika

**Comment by JensXII** [comment]
Sorry, Angelika, unfortunately on https://github.com/EuroMOMOnetwork there are no documentation.
The scripts and packages are primarily make for users, who know how to used them.

Are you interested in using the MOMO or FluMOMO package? – then please contact me, and I will be happy to help you.

Take care
  Jens
